name: Running azcopy 


on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Azcopy test
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          export AZCOPY_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["tenantId"]')
          export AZCOPY_AUTO_LOGIN_TYPE=SPN
          export AZCOPY_SPA_APPLICATION_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["clientId"]')
          export AZCOPY_SPA_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r '.["clientSecret"]')
          echo "::add-mask::$AZCOPY_SPA_APPLICATION_ID"
          echo "::add-mask::$AZCOPY_SPA_CLIENT_SECRET"
          azcopy copy dummy_file.txt https://iacstatestorage.blob.core.windows.net/demo/dummy_file.txt
